spring:
  application:
    name: Elchino
  data:
    mongodb:
      database: elchino
      uri: mongodb+srv://luislevanovega_db_user:q1txmTu7lZjaNk4o@pruebas.7ywmllo.mongodb.net/?appName=Pruebas

server:
  port: 8087
