spring:
  application:
    name: Elchino
  data:
    mongodb:
      #database: ${DATABASE_NAME}
      #uri: ${DATABASE_URI}
      database: elchino
      uri: mongodb+srv://user:secret123@cluster0.ygyqtee.mongodb.net/?appName=Cluster0
      #mongodb://3.94.200.168:27017
      #mongodb+srv://user:secret123@cluster0.ygyqtee.mongodb.net/?appName=Cluster0
server:
  port: 8087
