# kubectl apply -f freddy-quispe-12-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: freddy-quispe-12-secret
  namespace: freddy-quispe-12-namespace
type: Opaque
stringData:
  DATABASE: nosql   # en Base64
  URI: mongodb://user:secret123@ac-pglbjri-shard-00-00.ygyqtee.mongodb.net:27017,ac-pglbjri-shard-00-01.ygyqtee.mongodb.net:27017,ac-pglbjri-shard-00-02.ygyqtee.mongodb.net:27017/?ssl=true&replicaSet=atlas-uxyg6s-shard-0&authSource=admin&appName=Cluster0   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode