# kubectl apply -f juan-condori-00-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: juan-condori-00-secret
  namespace: juan-condori-00-namespace
type: Opaque
data:
  DATABASE: bm9zcWw=   # en Base64
  URI: bW9uZ29kYitzcnY6Ly9qdWFuOjEyMzQ1QGNsdXN0ZXIwLnpkbDluLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode