name: Trivy Security Scan

on:
  push:
    branches:
      - develop
      - webflux-nosql # puedes añadir más ramas
  pull_request:
    branches:
      - develop
      - webflux-nosql # puedes añadir más ramas
  schedule:
    # Ejecutar todos los días a las 8:00 AM hora Perú (UTC-5) → 1:00 PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions UI

jobs:

  trivy-security:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 16
          cache: maven

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0' # 0: No Falla por vulnerabilidades | 1: Falla por vulnerabilidades

      - name: Pipeline Finished
        run: echo "Trivy scan completed successfully"